### ISSUE TITLE
Build failed 🤷🥺

### ISSUE THREAD

**Issue by ilyar** [tonlabs/TON-Compiler#194]
[build.log](https://github.com/tonlabs/TON-Compiler/files/5968748/build.log)

Reproduction:
```
FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -qqy update
RUN apt-get -qqy install cmake ninja-build g++ git python curl zlib1g
RUN git clone --depth 1 https://github.com/tonlabs/ton-compiler.git /usr/src/ton-compiler
RUN mkdir /usr/src/ton-compiler/build
WORKDIR /usr/src/ton-compiler/build

RUN cmake \
    -G Ninja \
    -DLLVM_ENABLE_ASSERTIONS=1 \
    -DCMAKE_BUILD_TYPE="Release" \
    -DLLVM_BUILD_LLVM_DYLIB=1 \
    -DLLVM_LINK_LLVM_DYLIB=1 \
    -DLLVM_TARGETS_TO_BUILD="" \
    -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="TVM" \
    -DLLVM_BYTE_SIZE_IN_BITS=257 \
    -DLLVM_USE_LINKER=gold \
    ../llvm
RUN ninja
```

**Comment by azhogin** [comment]
`0.	Program arguments: /usr/src/ton-compiler/build/bin/llvm-tblgen -gen-dag-isel -I /usr/src/ton-compiler/llvm/lib/Target/TVM -I /usr/src/ton-compiler/llvm/include -I /usr/src/ton-compiler/llvm/lib/Target /usr/src/ton-compiler/llvm/lib/Target/TVM/TVM.td -o lib/Target/TVM/TVMGenDAGISel.inc.tmp -d lib/Target/TVM/TVMGenDAGISel.inc.d 
Aborted (core dumped)
[1124/2523] Building TVMGenRegisterInfo.inc...
[1125/2523] Building CXX object lib/Target/CMakeFiles/LLVMTarget.dir/TargetIntrinsicInfo.cpp.o
[1126/2523] Building TVMGenInstrInfo.inc...
FAILED: lib/Target/TVM/TVMGenInstrInfo.inc.tmp 
cd /usr/src/ton-compiler/build && /usr/src/ton-compiler/build/bin/llvm-tblgen -gen-instr-info -I /usr/src/ton-compiler/llvm/lib/Target/TVM -I /usr/src/ton-compiler/llvm/include -I /usr/src/ton-compiler/llvm/lib/Target /usr/src/ton-compiler/llvm/lib/Target/TVM/TVM.td -o lib/Target/TVM/TVMGenInstrInfo.inc.tmp -d lib/Target/TVM/TVMGenInstrInfo.inc.d
Type set is empty for each HW mode:
possible type contradiction in the pattern below (use -print-records with llvm-tblgen to see all expanded records).
DICTUMAXREF: 	(DICTUMAXREF:{ *:[TVMCell] }:{ *:[i257] }:{ *:[i257] } Cell:{ *:[TVMCell] }:$dict, I257:{ *:[i257] }:$precision)
UNREACHABLE executed at /usr/src/ton-compiler/llvm/utils/TableGen/CodeGenDAGPatterns.cpp:817!`

**Comment by ilyar** [comment]
@azhogin что тут можно сделать, какие правметры сборки? может надо использовать другую ревизию?

**Comment by VasiliyKuznetsov** [comment]
```
FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -qqy update
RUN apt-get -qqy install cmake ninja-build g++ git python curl zlib1g cargo
RUN git clone --depth 1 https://github.com/tonlabs/ton-compiler.git /usr/src/ton-compiler
RUN mkdir /usr/src/ton-compiler/build
WORKDIR /usr/src/ton-compiler/build

RUN cmake -G Ninja -C ../cmake/Cache/ton-compiler.cmake ../llvm
RUN ninja -j6
```
так собирается
