### ISSUE TITLE
git clone git@github.com:tonlabs/TON-Compiler.git error

### ISSUE THREAD

**Issue by TehnobitSystems** [tonlabs/TON-Compiler#196]
freeton:~/ton# git clone git@github.com:tonlabs/TON-Compiler.git
Cloning into 'TON-Compiler'...
The authenticity of host 'github.com (140.82.121.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,140.82.121.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Work fine: 
git clone https://github.com/tonlabs/TON-Compiler.git

**Comment by joydark** [comment]
Did you set up your GitHub keys?
GitHub requires it in order to authenticate you as user and only then it allows to clone via `git clone git@github.com:tonlabs/TON-Compiler.git`
